[package]
name = "five"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoclib = { path = "../lib" }
nom = "7.1.3"
rayon = "1.8.1"
rand = "0.8.5"